// eslint-disable-next-line
export const LIST_ACTIONS = {
  ITEM_PREVIEW: 'ITEM_PREVIEW',
  ITEM_VIEW: 'ITEM_VIEW',
  ITEM_ADD: 'ITEM_ADD',
  ITEM_CLEAR: 'ITEM_CLEAR',
};

export const AUTH_ACTIONS = {
  SET_IS_AUTHENTICATED: 'SET_IS_AUTHENTICATED',
  TOKEN_SET: 'TOKEN_ADD',
  AUTHORIZE_URI_SET: 'AUTHORIZE_URI_SET',
};
