// eslint-disable-next-line
export const AUTH_ACTIONS = {
  SET_IS_AUTHENTICATED: 'SET_IS_AUTHENTICATED',
  TOKEN_SET: 'TOKEN_ADD',
  AUTHORIZE_URI_SET: 'AUTHORIZE_URI_SET',
  SET_IS_EDITABLE: 'SET_IS_EDITABLE',
  SET_LTI_REQUEST: 'SET_LTI_REQUEST',
  SET_JWT_TOKEN: 'SET_JWT_TOKEN',
};

export const ROSTER_ACTIONS = {
  SET_ROLE: 'SET_ROLE',
  SET_PSEUDONYM: 'SET_PSEUDONYM',
  SET_GROUP: 'SET_GROUP',
  SET_STUDENTS: 'SET_STUDENTS',
  SET_TEACHERS: 'SET_TEACHERS',
};
